config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :tags
  get '/', to: 'pages#index'
  post 'authenticate', to: 'authentication#authenticate'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :tag
  delegate :user, to: :tag, allow_nil: true

  before_validation :set_default_values
  after_create_commit { ActivityBroadcastJob.perform_later self }

  default_scope { order(created_at: :desc) }

  scope :finished, -> { where.not(end_time: nil) }
  scope :doing, -> { where(end_time: nil) }
  scope :today, -> { where("start_time >= ?", Time.current.beginning_of_day) }
  scope :week, -> { where("start_time >= ?", Time.current.beginning_of_week) }
  scope :month, -> { where("start_time >= ?", Time.current.beginning_of_month) }

  validates_presence_of :start_time

  def finish!(time = Time.current)
    self.end_time = time
    save
  end

  private

  def set_default_values
    self.start_time ||= Time.current
    self.duration = (self.end_time - self.start_time).ceil if self.start_time && self.end_time
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :activities
  belongs_to :user

  validates_uniqueness_of :rfid, scope: :user_id
  validates_uniqueness_of :name, scope: :user_id
  validates_presence_of :user_id, :rfid

  def name
    self[:name] || rfid
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tags
  has_many :activities, through: :tags

  validates_uniqueness_of :email

  PieActivitiy = Struct.new(:sum, :colour, :name)

  # Returns a hash which can be used to generate a PieChart
  # with chart.js
  # For example:
  # {
  #   labels: ["Red", "Blue"],
  #   datasets: [{
  #       label: '# of Votes',
  #       data: [12, 19],
  #       backgroundColor: [
  #         'rgba(255, 99, 132, 0.2)',
  #         'rgba(54, 162, 235, 0.2)',
  #       ]
  #   }]
  # }
  def daily_doughnut_chart
    {
      labels: pie_data.map { |item| item.name },
      datasets: [{
        label: 'Today',
        data: pie_data.map { |item| item.sum },
        backgroundColor: background_colours(pie_data.map { |item| item.colour })
      }]
    }
  end

  def doing
    doing = activities.doing.includes(:tag).first
    doing ? doing.tag.name : 'n/a'
  end

  def log_in_time
    activities.today.last.try(:start_time)
  end

  private

  def background_colours(colours)
    colours.map { |colour| colour || "rgba(#{rand(0..255)}, #{rand(0..255)}, #{rand(0..255)}, 0.5)" }
  end

  def pie_data
    sum = activities.finished.today.group(:rfid).sum(:duration)
    user_tags = tags.where(rfid: sum.keys).select(:rfid, :name, :colour)
    result = []
    user_tags.each do |tag|
        result << PieActivitiy.new(sum[tag.rfid], tag.colour, tag.name) if sum[tag.rfid]
    end
    result
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    # TODO: Move to a dedicated dashboard controller
    result = {
      daily_doughnut_chart: @current_user.daily_doughnut_chart,
      doing: @current_user.doing,
      first_entry_today: @current_user.log_in_time,
      total_entries_today: @current_user.activities.today.count,
      hours_today: @current_user.activities.today.sum(:duration)
    }
    render json: result.to_json
  end

  # POST /activities
  # POST /activities.json
  def create
    @current_user.activities.doing.map { |activity| activity.finish! }
    tag = Tag.find_or_initialize_by(rfid: params[:rfid].chomp, user: @current_user)
    @activity = tag.activities.build

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:start_time, :end_time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :null_session
  before_action :authenticate_request
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])
    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_request, only: :index

  def index; end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:rfid, :name, :colour)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :activity_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :activity_end_time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :activity_duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.start_time %></td>
        <td><%= activity.end_time %></td>
        <td><%= activity.duration %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @activity.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @activity.end_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= react_component 'main' %>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rfid %>
    <%= form.text_field :rfid, id: :tag_rfid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour, id: :tag_colour %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Rfid</th>
      <th>Name</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.rfid %></td>
        <td><%= tag.name %></td>
        <td><%= tag.colour %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rfid:</strong>
  <%= @tag.rfid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @tag.colour %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>